### ISSUE TITLE
:tada: (:open_umbrella:): NeoNix project requirements

### ISSUE THREAD

**Issue by RAPSNX** [rgroemmer/neonix#1]
This umbrella issue will track the progress for `NeoNix`.

- #10 

- [x] Battleproofd

There are multiple toplevel `categories` which contain multiple `features`.

## :sparkle: :100: First release
- [x] remove `flake-parts`
- [x] restructure like `dotfiles`
- [x] modulize if needed
- [x] test / validate go debugging
- [x] Update readme w/keybindings + docs
- [x] Beautify readme like `dotfiles`

## :wrench: General configuration

- [x] lsp #6 
- [x] keymappings #4 
- [x] core config #3
- [x] reuse configuration from `neovim` #3 #4 
- [x] cmp 
- [x] autocmds
- [x] autoclose brackets / auto jump body
- [x] check all open points here

## :heavy_plus_sign: Plugin configuration

- [x] bufferline #4 
- [x] treesitter #4 
- [x] telescope #4 
- [x] diagnosics
- [x] lazygit

## :alien: Language support

- [x] golang #2
- [x] yaml #6 
- [x] terraform
- [x] nix #6 

## :lipstick: Make it beautiful

- [x] colorscheme #4
  - [x] neovim #4 
  - [x] plugins #4 
- [x] Bufferline style + data #4

## :100: improvements
- [x] better goto definition / `gopls` config
- [x] yaml schemas, no errors in `helmrelease`
- [x] readme update w/shortcuts
- [x] make intellisense only three symbols
- [x] better file-management, wider tree

## :star: :star: MILESTONES

- [x] Make it runnable via `nix run`
- [x] Add integration for `home-manager` #5 
- [x] Release 0.1.0
